version: '3'

services:
  db:
    image: mysql:5.6
    restart: always
    volumes:
      - wp_bedrock_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: w0rdpr355
      MYSQL_RANDOM_ROOT_PASSWORD: r00tr00t

  wordpress:
    depends_on:
      - db
    build:
      context: .
    image: wp-bedrock
    restart: always
    links:
      - db
    ports:
      - 8000:80
    environment:
      DB_NAME: wordpress
      DB_USER: wp
      DB_PASSWORD: w0rdpr355
      DB_HOST: db
      WP_ENV: development
      WP_HOME: http://localhost:8000
      WP_SITEURL: http://localhost:8000/wp
      AUTH_KEY: generateme
      SECURE_AUTH_KEY: generateme
      LOGGED_IN_KEY: generateme
      NONCE_KEY: generateme
      AUTH_SALT: generateme
      SECURE_AUTH_SALT: generateme
      LOGGED_IN_SALT: generateme
      NONCE_SALT: generateme

volumes:
  wp_bedrock_data: